# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b448164430248b6b4b185d1569d543c3c529bc8b71c3e135a984d82157d4e498be67175ddac112fb8c12439b4f7d9c43889af609406854974adee96d89c3b33

test:
  secret_key_base: 6b00ec2d4f67a5883ec362b33e9091a83f09414b911a3142da1d26013a29266024c349509e4f2f69ced64fae4415a79eacbd78c085086c656de6e7b4a415dc7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
